[tool.ruff]
target-version = "py310"
# 启用核心规则集
line-length = 120
select = ["E", "F", "W", "I", "N", "ANN"] # ANN为类型注解规则，N强制执行PEP8命名规范，I自动排序import语句
ignore = ["E501", "D413", "D103"]
extend-include = ["*.ipynb"]

[tool.ruff.lint]
# 启用文档字符串规则
extend-select = ["D"]
# 强制要求公共函数有类型注解
# require-annotations = true
# 自动修复缺失的类型注解
# annotate-missing = true
# 要求公共函数有docstring
# require-docstrings = true
# 自动修复缺失的docstring模板
# docstring-convetion = "google"

[tool.ruff.format]
indent-style = "space"

[tool.ruff.isort]
# 按类型分组排序import
# profile = "black"

[tool.jupytext]
formats = "ipynb,py:percent"
notebook_metadata_filter = "jupytext,-kernelspec,-jupytext.text_representation.jupytext_version"
cell_metadata_filter="-all"
outdated_text_notebook_margin = 5
