[tool.ruff]
line-length = 120
select = ["E", "F", "I", "B"]
[tool.ruff.format]
indent-style = "space"

[tool.jupytext]
formats = "ipynb,py:percent"
notebook_metadata_filter = "jupytext,-kernelspec,-jupytext.text_representation.jupytext_version"
cell_metadata_filter="-all"
outdated_text_notebook_margin = 5
